language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
matrix:
  include:
    # The perl does not matter here, system perl will be used
    - perl: "5.18"
      os: osx
      sudo: true
    - perl: "5.18"
      dist: trusty

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install cpanminus; fi
install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cpanm --sudo --quiet --installdeps --notest .; else cpanm --quiet --installdeps --notest .; fi

branches:
 except:
  - /appveyor/
sudo: false
